### ISSUE TITLE
[L4D2]Signature addition/support request

### ISSUE THREAD

**Issue by umlka** [Psykotikism/L4D1-2_Signatures#2]
/* ForEachTerrorPlayer<SpawnablePZScan>(SpawnablePZScan &) */
"ForEachTerrorPlayer<SpawnablePZScan>"
{
	"library"	"server"
	"linux"	"@_Z19ForEachTerrorPlayerI15SpawnablePZScanEbRT_"
}

sub_10356A50
The Windows signature is in this function, makesig reports me an error Ran out of bytes to create unique signature.

**Comment by Psykotikism** [comment]
I tried, but unfortunately, the function's bytes are not unique enough for wildcards. I could only get the raw bytes.
```pawn
Signature for calling sub_10356A50:
"\x55\x8B\xEC\xA1\x90\x35\x7F\x10\x53\x56\x57\xBF\x01\x00\x00\x00\x39\x78\x14\x7C\x5A\x8B\x5D\x08\x57\xE8\x32\xFE"
/* 55 8B EC A1 90 35 7F 10 53 56 57 BF 01 00 00 00 39 78 14 7C 5A 8B 5D 08 57 E8 32 FE */
```
This will most likely break in a future update.

**Comment by umlka** [comment]
> I tried, but unfortunately, the function's bytes are not unique enough for wildcards. I could only get the raw bytes.
> 
> ```pawn
> Signature for calling sub_10356A50:
> "\x55\x8B\xEC\xA1\x90\x35\x7F\x10\x53\x56\x57\xBF\x01\x00\x00\x00\x39\x78\x14\x7C\x5A\x8B\x5D\x08\x57\xE8\x32\xFE"
> /* 55 8B EC A1 90 35 7F 10 53 56 57 BF 01 00 00 00 39 78 14 7C 5A 8B 5D 08 57 E8 32 FE */
> ```
> 
> This will most likely break in a future update.

Thank you so much, the Psykotikism. signature is valid

**Comment by Psykotikism** [comment]
Awesome, I'll add it to the repository soon.

**Comment by umlka** [comment]
emmm... Yesterday, the signature was valid when I tested it with escsig_search.idc, but it could not be loaded when I tested it on the Windows server just now.

**Comment by Psykotikism** [comment]
Do you have a sample plugin I can test with?

**Comment by umlka** [comment]
> Do you have a sample plugin I can test with?

https://github.com/umlka/l4d2/tree/main/control_zombies

**Comment by Psykotikism** [comment]
> https://github.com/umlka/l4d2/tree/main/control_zombies

~~You're not using the same signature I provided.
https://github.com/umlka/l4d2/blob/main/control_zombies/control_zombies.txt#L127-L128~~

I tried the plugin with my signature. It fails to detour the function. I'm not sure why since I even tried changing the detour's setup.

**Comment by umlka** [comment]
Yes, So I am now trying to detour all the functions that call it, but ZSpawnCore seems to be unable to detour it. I have now detour Script_ZSpawn, z_spawn_old and z_spawn. According to the current test, it can achieve the function I want.

**Comment by Psykotikism** [comment]
> Yes, So I am now trying to detour all the functions that call it, but ZSpawnCore seems to be unable to detour it. I have now detour Script_ZSpawn, z_spawn_old and z_spawn. According to the current test, it can achieve the function I want.

I'll work on adding/supporting signatures for those functions.

**Comment by umlka** [comment]
> > Yes, So I am now trying to detour all the functions that call it, but ZSpawnCore seems to be unable to detour it. I have now detour Script_ZSpawn, z_spawn_old and z_spawn. According to the current test, it can achieve the function I want.
> 
> I'll work on adding/supporting signatures for those functions.

Thanks, Psykotikism

**Comment by Psykotikism** [comment]
Just added support for several functions, including all the ones mentioned above.

**Comment by umlka** [comment]
>Just added support for several functions, including all the ones mentioned above.

Thank you, I have updated all my plugins that use these signatures
